version: "3.7"
services:
  gogolook:
    image: ${REPO}/${CONTAINER}:${TAG}
    container_name: ${CONTAINER}
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ~/volumes/gogolook:/usr/src/module/logs
      - ~/etc/timezone:/etc/localtime:ro
    ports: 
      - ${PORT}:${PORT}
    env_file:
      - ${ENV}
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:${PORT}/healthCheck || exit 1"]
      interval: 60s
      timeout: 10s
      start_period: 10s
    restart: always
